package v1ch03;


//变量名必须是由letters或者digits构成的序列，以字母开头

//letters :  'A'–'Z' , 'a'–'z' , '_' , '$'等，'$'虽然合法但是不要使用。
//digits :    0-9等

//变量名的长度无限制

//you can use the isJavaIdentifierStart and isJavaIdentifierPart methods in the Character class to check.


//Even though $ is a valid Java letter, you should not use it in your own code. It is intended for names that are generated by the Java compiler and other tools.


//变量名不要使用Java保留字(reserved word).

//变量名都是 case sensitive

public class VariableNameDemo {

    //类常量，可以在该类的多个方法中使用，使用static final标记，如果是public，可以被其他类的方法使用
    //const虽然是关键字，但是没有被使用
    public static final double CM_PER_INCH = 2.54;

    public static void main(String[] args) {
        char c = '%';
        System.out.println(Character.isJavaIdentifierPart(c));

        char c1 = '2';
        System.out.println(Character.isJavaIdentifierStart(c1));

        char c2 = '_';
        System.out.println(Character.isJavaIdentifierPart(c2));

        char c3 = 'ä';
        System.out.println(Character.isJavaIdentifierPart(c3));

        double paperWidth = 8.5;
        double paperHeight = 11;
        System.out.println("Paper size in centimeters:" + paperWidth * CM_PER_INCH + " by " + paperHeight * CM_PER_INCH);

        //习惯上，常量名使用全部大写，使用final标记常量
        final double CONST_NUM = 3.14;
        System.out.println(CONST_NUM);

        System.out.println(CM_PER_INCH);
    }

}
